import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#090A10',
  },
  heroBannerContainer: {
    height: 230,
    width: '100%',
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(9, 10, 16, 0.72)',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: 12,
  },
  backButtonFloating: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroContent: {
    marginBottom: 4,
  },
  playlistTagLabel: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 4,
  },
  heroSubtitle: {
    color: '#D1D5DB',
    fontSize: 14,
    fontWeight: '400',
  },
  dividerLine: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginHorizontal: 16,
    marginVertical: 4,
  },
  categoryBadgeRed: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  categoryBadgeRedText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '700',
  },
  metaTextLight: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '500',
  },
  dotMeta: {
    color: '#6B7280',
    fontSize: 12,
  },
  actionBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 8,
  },
  playAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EF4444',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 24,
    gap: 6,
  },
  playAllText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  actionIconButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1D27',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 24,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  actionIconLabel: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  iconOnlyButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#1C1D27',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  playlistDescriptionContainer: {
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  playlistDescriptionText: {
    color: '#9CA3AF',
    fontSize: 14,
    fontWeight: '400',
    lineHeight: 20,
  },
  sectionTitleHeader: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    paddingHorizontal: 16,
    marginTop: 6,
    marginBottom: 12,
  },
  playlistItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 14,
  },
  itemThumbWrap: {
    position: 'relative',
    width: 120,
    height: 70,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#1E1E2E',
  },
  itemThumb: {
    width: '100%',
    height: '100%',
  },
  durationBadge: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  itemDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  itemTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 4,
  },
  itemMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  itemMetaText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '400',
  },
});
