import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  card: {
    width: 155,
    marginRight: 12,
    marginBottom: 12,
  },
  cardFullWidth: {
    width: '48%',
    marginRight: 0,
    marginBottom: 18,
  },
  thumbnailWrap: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  thumbnailWrapFullWidth: {
    height: 115,
  },
  thumbnail: {
    width: '100%',
    height: '100%',
  },
  playBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    color: colors.text,
    fontSize: 10,
    fontWeight: '900',
    marginLeft: 1,
  },
  durationBadge: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  statusBadge: {
    position: 'absolute',
    left: 7,
    bottom: 7,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
  },
  statusText: {
    color: colors.text,
    fontSize: 8,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  videoTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
    lineHeight: 17,
  },
  descriptionText: {
    color: '#9CA3AF',
    fontSize: 11,
    lineHeight: 15,
    marginTop: 3,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 4,
    gap: 4,
  },
  category: {
    color: colors.primary || '#6366F1',
    fontSize: 10,
    fontWeight: '700',
  },
  dot: {
    color: '#6B7280',
    fontSize: 8,
  },
  meta: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '500',
  },
  uploadedTimeText: {
    color: '#9CA3AF',
    fontSize: 10,
    fontWeight: '500',
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    marginTop: 4,
  },
  tagPill: {
    backgroundColor: '#1E1E2D',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#2A2A3C',
  },
  tagText: {
    color: '#818CF8',
    fontSize: 9,
    fontWeight: '600',
  },
  watchProgressWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  watchProgressFill: {
    height: 4,
    backgroundColor: '#E50914',
  },
  watchProgressBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(229, 9, 20, 0.9)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  watchProgressBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#1A1A28',
  },
  actionBtnMini: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    padding: 2,
  },
  encodeProgressWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  encodeProgressFill: {
    height: 3,
    backgroundColor: '#3B82F6',
  },
  deleteBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 20,
  },
  rowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 16,
    gap: 12,
  },
  rowThumbnailWrap: {
    width: 125,
    height: 80,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: colors.surface,
  },
  rowDetails: {
    flex: 1,
    justifyContent: 'center',
  },
  rowTitle: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
    marginBottom: 6,
  },
  rowMetaLine: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 5,
  },
  rowCategory: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '600',
  },
  rowDot: {
    color: '#6B7280',
    fontSize: 10,
  },
  rowMeta: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '500',
  },
});