import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    height: 64,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  headerTitle: { color: colors.text, fontSize: 20, fontWeight: '800' },
  headerSpacer: { width: 40 },
  emptyState: {
    flex: 1,
    paddingHorizontal: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  list: { padding: 16, gap: 12 },
  collectionContent: { paddingBottom: 28 },
  playerArea: { width: '100%', height: 215, backgroundColor: '#000000' },
  upNextTitle: { marginHorizontal: 16, marginTop: 20, marginBottom: 8, color: colors.text, fontSize: 17, fontWeight: '800' },
  videoRow: { minHeight: 82, padding: 10, borderRadius: 14, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface },
  thumbnail: { width: 96, height: 60, borderRadius: 9, backgroundColor: '#252532' },
  thumbnailFallback: { width: 96, height: 60, borderRadius: 9, backgroundColor: '#252532' },
  videoCopy: { flex: 1, marginLeft: 12 },
  videoTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  videoDescription: { marginTop: 5, color: colors.muted, fontSize: 12 },
  iconWrap: {
    width: 72,
    height: 72,
    marginBottom: 18,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,36,94,0.12)',
  },
  emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  emptyDescription: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  exploreButton: {
    marginTop: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.primary,
  },
  exploreButtonText: { color: colors.text, fontSize: 14, fontWeight: '800' },
  tabsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    gap: 10,
  },
  tabButton: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#181926',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  activeTabButton: {
    backgroundColor: '#6366F1',
    borderColor: '#6366F1',
  },
  tabButtonText: {
    color: '#9CA3AF',
    fontSize: 13,
    fontWeight: '600',
  },
  activeTabButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  playlistRow: {
    minHeight: 84,
    padding: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
  },
  playlistThumbnail: {
    width: 100,
    height: 64,
    borderRadius: 10,
    backgroundColor: '#1E1E2E',
  },
  playlistCopy: {
    flex: 1,
    marginLeft: 14,
  },
  playlistTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  playlistMeta: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 12,
  },
  shortsGrid: {
    padding: 16,
    paddingBottom: 40,
  },
  shortCard: {
    width: '48%',
    borderRadius: 14,
    marginBottom: 14,
    overflow: 'hidden',
  },
  shortThumbnailWrapper: {
    width: '100%',
    aspectRatio: 9 / 14,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#1E1E2E',
    position: 'relative',
  },
  shortThumbnail: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  shortBadgeOverlay: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(0,0,0,0.65)',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  shortViewsText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  shortCopy: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  shortTitle: {
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 17,
  },
  shortMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
});
