import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    height: 64,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  headerTitle: { color: colors.text, fontSize: 20, fontWeight: '800' },
  headerSpacer: { width: 40 },
  emptyState: {
    flex: 1,
    paddingHorizontal: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  list: { padding: 16, gap: 12 },
  collectionContent: { paddingBottom: 28 },
  playerArea: { width: '100%', height: 215, backgroundColor: '#000000' },
  upNextTitle: { marginHorizontal: 16, marginTop: 20, marginBottom: 8, color: colors.text, fontSize: 17, fontWeight: '800' },
  videoRow: { minHeight: 82, padding: 10, borderRadius: 14, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface },
  thumbnail: { width: 96, height: 60, borderRadius: 9, backgroundColor: '#252532' },
  thumbnailFallback: { width: 96, height: 60, borderRadius: 9, backgroundColor: '#252532' },
  videoCopy: { flex: 1, marginLeft: 12 },
  videoTitle: { color: colors.text, fontSize: 14, fontWeight: '700' },
  videoDescription: { marginTop: 5, color: colors.muted, fontSize: 12 },
  iconWrap: {
    width: 72,
    height: 72,
    marginBottom: 18,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,36,94,0.12)',
  },
  emptyTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  emptyDescription: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  exploreButton: {
    marginTop: 24,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.primary,
  },
  exploreButtonText: { color: colors.text, fontSize: 14, fontWeight: '800' },
});
