import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#242436',
    paddingBottom: 24,
  },
  sectionHeader: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 16,
  },
  loadingContainer: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  emptyContainer: {
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    color: '#9CA3AF',
    fontSize: 13,
    textAlign: 'center',
  },
  commentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
    gap: 10,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#374151',
  },
  commentMain: {
    flex: 1,
  },
  authorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  authorName: {
    color: '#F9FAFB',
    fontSize: 13,
    fontWeight: '700',
  },
  timeText: {
    color: '#9CA3AF',
    fontSize: 11,
  },
  commentText: {
    color: '#E5E7EB',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 4,
  },
  mentionText: {
    color: '#60A5FA',
    fontWeight: '600',
    fontSize: 13,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 2,
    marginBottom: 4,
  },
  actionLink: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '600',
  },
  actionDot: {
    color: '#4B5563',
    fontSize: 10,
  },
  heartColumn: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: 6,
    paddingTop: 2,
    minWidth: 28,
  },
  heartCountText: {
    color: '#9CA3AF',
    fontSize: 11,
    marginTop: 2,
    textAlign: 'center',
  },
  toggleRepliesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 4,
  },
  toggleRepliesLine: {
    width: 24,
    height: 1,
    backgroundColor: '#4B5563',
  },
  toggleRepliesText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
  },
  repliesContainer: {
    marginTop: 8,
    gap: 12,
  },
  replyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  replyAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#374151',
  },
  replyMain: {
    flex: 1,
  },
  replyAuthorName: {
    color: '#F9FAFB',
    fontSize: 12,
    fontWeight: '700',
  },
  replyText: {
    color: '#E5E7EB',
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 2,
  },
  bottomDockContainer: {
    marginTop: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#262638',
    backgroundColor: '#161622',
  },
  replyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingVertical: 6,
    marginBottom: 8,
  },
  replyHeaderText: {
    color: '#D1D5DB',
    fontSize: 13,
    fontWeight: '500',
  },
  inputFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#374151',
  },
  inputPillContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1C28',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#2E2E42',
    paddingHorizontal: 14,
    paddingVertical: 2,
  },
  textInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 13,
    paddingVertical: 8,
  },
  sendBtn: {
    backgroundColor: '#6366F1',
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: '#374151',
    opacity: 0.5,
  },
});
