import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#242436',
    paddingBottom: 24,
  },
  sectionHeader: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 16,
    letterSpacing: 0.2,
  },
  loadingContainer: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  emptyContainer: {
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    color: '#9CA3AF',
    fontSize: 13,
    textAlign: 'center',
  },
  commentCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
    gap: 12,
  },
  leftColumn: {
    alignItems: 'center',
    alignSelf: 'stretch',
    width: 34,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#374151',
  },
  threadLine: {
    width: 2,
    flex: 1,
    backgroundColor: '#37374D',
    marginTop: 6,
    borderRadius: 1,
  },
  commentMain: {
    flex: 1,
  },
  authorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  authorInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    flexWrap: 'wrap',
  },
  authorName: {
    color: '#F3F4F6',
    fontSize: 13,
    fontWeight: '700',
  },
  timeText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '400',
  },
  moreBtn: {
    padding: 2,
  },
  commentText: {
    color: '#F1F5F9',
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 6,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 2,
    marginBottom: 6,
  },
  actionIconButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 2,
  },
  actionCountText: {
    color: '#AAAAAA',
    fontSize: 12,
    fontWeight: '600',
  },
  creatorHeartContainer: {
    position: 'relative',
    width: 22,
    height: 22,
    justifyContent: 'center',
    alignItems: 'center',
  },
  creatorAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#374151',
  },
  creatorHeartBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    backgroundColor: '#EF4444',
    width: 11,
    height: 11,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#12121A',
  },
  replyBtnText: {
    color: '#F3F4F6',
    fontSize: 12,
    fontWeight: '600',
  },
  toggleRepliesBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 6,
    marginBottom: 6,
  },
  miniReplyAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#374151',
  },
  toggleRepliesText: {
    color: '#F3F4F6',
    fontSize: 13,
    fontWeight: '700',
  },
  repliesContainer: {
    marginTop: 10,
    gap: 14,
    paddingLeft: 4,
  },
  replyCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  replyLeftColumn: {
    alignItems: 'center',
    width: 26,
  },
  replyAvatar: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#374151',
  },
  replyMain: {
    flex: 1,
  },
  creatorPillBadge: {
    backgroundColor: '#272738',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    alignSelf: 'flex-start',
  },
  creatorPillText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  replyAuthorName: {
    color: '#F3F4F6',
    fontSize: 12,
    fontWeight: '700',
  },
  replyText: {
    color: '#F1F5F9',
    fontSize: 12,
    lineHeight: 17,
    marginVertical: 4,
  },
  mentionText: {
    color: '#38BDF8',
    fontWeight: '600',
    fontSize: 12,
  },
  bottomDockContainer: {
    marginTop: 16,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#262638',
    backgroundColor: '#161622',
  },
  replyHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    paddingVertical: 6,
    marginBottom: 8,
  },
  replyHeaderText: {
    color: '#D1D5DB',
    fontSize: 13,
    fontWeight: '500',
  },
  inputFieldRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#374151',
  },
  inputPillContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1C1C28',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#2E2E42',
    paddingHorizontal: 14,
    paddingVertical: 2,
  },
  textInput: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 13,
    paddingVertical: 8,
  },
  sendBtn: {
    backgroundColor: '#6366F1',
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    backgroundColor: '#374151',
    opacity: 0.5,
  },
});
