import { StyleSheet } from 'react-native';

export const PLAYER_COLORS = {
  white: '#FFFFFF',
  mutedWhite: 'rgba(255,255,255,0.72)',
  progressTrack: 'rgba(255,255,255,0.35)',
  progressFill: '#FF0000',
  accent: '#FF0000',
};

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
    position: 'relative',
    overflow: 'hidden',
  },
  player: {
    width: '100%',
    height: '100%',
  },
  touchOverlay: {
    ...StyleSheet.absoluteFill,
    zIndex: 10,
    elevation: 10,
    backgroundColor: 'transparent',
  },
  controlsLayer: {
    ...StyleSheet.absoluteFill,
    zIndex: 999,
    elevation: 999,
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
  topBar: {
    minHeight: 56,
    paddingHorizontal: 14,
    paddingTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  topBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  topIconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playerTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
    flex: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },

  /* Autoplay Pill Toggle Switch */
  autoplaySwitchTrack: {
    width: 44,
    height: 22,
    borderRadius: 11,
    padding: 2,
    justifyContent: 'center',
  },
  autoplayTrackOn: {
    backgroundColor: 'rgba(255, 255, 255, 0.45)',
  },
  autoplayTrackOff: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  autoplayKnob: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 2,
  },
  autoplayKnobRight: {
    alignSelf: 'flex-end',
  },
  autoplayKnobLeft: {
    alignSelf: 'flex-start',
  },

  /* Pill & Badge Buttons */
  ytIconButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ytIconButtonActive: {
    backgroundColor: '#FF0000',
  },
  ccBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  darkCcText: {
    color: '#0F0F0F',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.5,
  },

  /* Center Play/Pause & Skip Controls */
  centerControlsRow: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 28,
  },
  ytCenterPlayButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIconOffset: {
    marginLeft: 1,
  },
  centerPlayIconOffset: {
    marginLeft: 3,
  },
  ytSkipButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ytSkipText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '800',
    marginTop: 1,
  },

  centerOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    elevation: 1000,
  },
  bottomPanel: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
    backgroundColor: 'transparent',
  },
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  progressAndTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  timeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  downloadProgressText: {
    color: '#FF0000',
    fontSize: 11,
    fontWeight: '700',
  },
  progressBarWrapperFlex: {
    flex: 1,
    height: 22,
    justifyContent: 'center',
  },
  progressBarWrapperInLine: {
    flex: 1,
    height: 22,
    justifyContent: 'center',
  },
  progressBarBackground: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    overflow: 'visible',
  },
  progressBarFill: {
    height: 4,
    borderRadius: 2,
    backgroundColor: '#FF0000',
  },
  progressThumb: {
    position: 'absolute',
    top: -5,
    width: 14,
    height: 14,
    marginLeft: -7,
    borderRadius: 7,
    backgroundColor: '#FF0000',
  },
  bottomActions: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  bottomRightGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionButton: {
    minWidth: 32,
    height: 30,
    borderRadius: 15,
    paddingHorizontal: 8,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  volumeControlRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  volumeSliderWrapper: {
    width: 60,
    height: 32,
    justifyContent: 'center',
    marginLeft: 4,
    marginRight: 8,
  },
  volumeSliderBg: {
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 2,
    position: 'relative',
    justifyContent: 'center',
  },
  volumeSliderFill: {
    height: '100%',
    backgroundColor: '#FF0000',
    borderRadius: 2,
    position: 'absolute',
    left: 0,
    top: 0,
  },
  volumeSliderThumb: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#FFFFFF',
    position: 'absolute',
    marginLeft: -5,
  },
  errorBox: {
    maxWidth: '80%',
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: 'rgba(18, 18, 18, 0.95)',
    alignItems: 'center',
  },
  errorText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 12,
  },
  retryButton: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  retryText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },

  /* YouTube-Style Settings Bottom Sheet (Matching user screenshot) */
  sheetBackdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
    zIndex: 2000,
    elevation: 2000,
  },
  sheetBackdropTouch: {
    flex: 1,
  },
  sheetContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingTop: 10,
    paddingBottom: 28,
    paddingHorizontal: 16,
    maxHeight: '85%',
    width: '100%',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  grabHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
    marginBottom: 12,
  },
  sheetMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 8,
  },
  sheetMenuLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  sheetMenuTitle: {
    color: '#0F0F0F',
    fontSize: 15,
    fontWeight: '600',
  },
  sheetMenuRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  sheetMenuValue: {
    color: '#606060',
    fontSize: 14,
    fontWeight: '400',
  },
  sheetSubHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    marginBottom: 8,
    gap: 12,
  },
  sheetSubTitle: {
    color: '#0F0F0F',
    fontSize: 16,
    fontWeight: '700',
  },
  sheetOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 13,
    paddingHorizontal: 8,
  },
  sheetOptionText: {
    color: '#0F0F0F',
    fontSize: 14,
    fontWeight: '500',
  },
  sheetOptionTextActive: {
    color: '#000000',
    fontWeight: '800',
  },
  sheetOptionCheckMark: {
    color: '#0F0F0F',
    fontSize: 15,
    fontWeight: '800',
  },

  /* Lock Overlay Screen */
  lockOverlay: {
    position: 'absolute',
    top: 24,
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    zIndex: 3000,
    elevation: 3000,
  },
  lockOverlayText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },

  /* Small Download Completed Toast Box */
  downloadToast: {
    position: 'absolute',
    bottom: 36,
    alignSelf: 'center',
    backgroundColor: 'rgba(18, 18, 18, 0.92)',
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    zIndex: 3500,
    elevation: 3500,
  },
  downloadToastText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },

  /* Subtitle Text Overlay */
  subtitleOverlayContainer: {
    position: 'absolute',
    bottom: 58,
    left: 20,
    right: 20,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 900,
    elevation: 900,
  },
  subtitleTextBackground: {
    backgroundColor: 'rgba(0, 0, 0, 0.78)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 8,
    maxWidth: '92%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  subtitleText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 20,
    textShadowColor: '#000000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
});
