import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
    screen: {
        flex: 1,
        backgroundColor: colors.background,
        justifyContent: 'center',
    },
    glowBlob: {
        position: 'absolute',
        width: 300,
        height: 300,
        borderRadius: 150,
        opacity: 0.15,
    },
    blob1: {
        top: -50,
        right: -50,
        backgroundColor: colors.primary,
    },
    blob2: {
        bottom: -50,
        left: -50,
        backgroundColor: '#3B82F6', // Sleek blue highlight
    },
    content: {
        flex: 1,
        paddingHorizontal: 24,
        justifyContent: 'space-between',
        paddingVertical: 40,
    },
    logoContainer: {
        alignItems: 'center',
        marginTop: 60,
    },
    logoGlow: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: 'rgba(255, 36, 94, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 12,
        elevation: 8,
    },
    logoText: {
        color: colors.text,
        fontSize: 36,
        fontWeight: '900',
        letterSpacing: 1,
    },
    tagline: {
        color: colors.muted,
        fontSize: 14,
        marginTop: 6,
        fontWeight: '500',
    },
    card: {
        backgroundColor: colors.surface,
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.05)',
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.5,
        shadowRadius: 16,
        elevation: 10,
    },
    cardTitle: {
        color: colors.text,
        fontSize: 22,
        fontWeight: '800',
        marginBottom: 8,
        textAlign: 'center',
    },
    cardSubtitle: {
        color: colors.muted,
        fontSize: 14,
        lineHeight: 20,
        textAlign: 'center',
        marginBottom: 28,
        paddingHorizontal: 10,
    },
    loginButton: {
        backgroundColor: colors.primary,
        borderRadius: 14,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    loginButtonPressed: {
        opacity: 0.85,
        transform: [{ scale: 0.98 }],
    },
    loginButtonText: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '700',
    },
    footer: {
        alignItems: 'center',
    },
    footerText: {
        color: colors.muted,
        fontSize: 12,
        fontWeight: '600',
        opacity: 0.6,
    },
});
