org.gradle.jvmargs=-Xmx1536m -Xms256m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx384m
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1

reactNativeArchitectures=arm64-v8a,x86_64

android.useAndroidX=true
android.enableJetifier=false
hermesEnabled=true
newArchEnabled=true