org.gradle.jvmargs=-Xmx768m -Xms128m -XX:MaxMetaspaceSize=192m -XX:ReservedCodeCacheSize=64m -XX:+UseSerialGC -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx256m
kotlin.compiler.execution.strategy=in-process
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1

reactNativeArchitectures=arm64-v8a,x86_64

android.useAndroidX=true
android.enableJetifier=false
hermesEnabled=true
newArchEnabled=true