org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=512m -XX:TieredStopAtLevel=1 -XX:HeapBaseMinAddress=32g -Dfile.encoding=UTF-8

kotlin.daemon.jvmargs=-Xmx384m

kotlin.compiler.execution.strategy=in-process

org.gradle.daemon=false

org.gradle.parallel=false

org.gradle.workers.max=1
reactNativeArchitectures=arm64-v8a
android.useAndroidX=true
android.enableJetifier=false
hermesEnabled=true
newArchEnabled=true