import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0F0F17',
  },
  heroBannerContainer: {
    height: 280,
    width: '100%',
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
  },
  heroOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(15, 15, 23, 0.65)',
    justifyContent: 'space-between',
    padding: 16,
    paddingTop: 12,
  },
  backButtonFloating: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroContent: {
    marginBottom: 8,
  },
  playlistTag: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  heroTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    fontWeight: '900',
    marginBottom: 10,
  },
  heroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryPill: {
    backgroundColor: '#3F1219',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    borderColor: '#7F1D1D',
    borderWidth: 1,
  },
  categoryPillText: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: '700',
  },
  heroMetaText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '500',
  },
  dotMeta: {
    color: '#4B5563',
    fontSize: 12,
  },
  actionsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E2E',
  },
  playAllButton: {
    backgroundColor: '#E50914',
    paddingHorizontal: 20,
    paddingVertical: 11,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  playAllText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  actionOutlineBtn: {
    backgroundColor: '#1E1E2E',
    borderWidth: 1,
    borderColor: '#2A2A3E',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionOutlineText: {
    color: '#D1D5DB',
    fontSize: 13,
    fontWeight: '600',
  },
  descriptionSection: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1E1E2E',
  },
  descriptionText: {
    color: '#D1D5DB',
    fontSize: 13,
    lineHeight: 20,
  },
  showMoreToggle: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
  tagPillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  tagPillItem: {
    backgroundColor: '#1E1E2E',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
  },
  tagPillItemText: {
    color: '#9CA3AF',
    fontSize: 12,
    fontWeight: '600',
  },
  sectionTitleRow: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 10,
  },
  sectionTitleText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
  },
  playlistItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  itemIndexText: {
    color: '#6B7280',
    fontSize: 15,
    fontWeight: '700',
    width: 20,
    textAlign: 'center',
  },
  itemThumbWrap: {
    position: 'relative',
    width: 110,
    height: 65,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#1E1E2E',
  },
  itemThumb: {
    width: '100%',
    height: '100%',
  },
  durationBadge: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
  },
  durationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  itemDetails: {
    flex: 1,
  },
  itemTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
  },
  itemMetaText: {
    color: '#9CA3AF',
    fontSize: 11,
  },
});
