import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
    loadingScreen: {
        flex: 1,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
    },
    screen: {
        flex: 1,
        backgroundColor: colors.background,
    },
    header: {
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.05)',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        color: colors.text,
        fontSize: 18,
        fontWeight: '700',
    },
    headerPlaceholder: {
        width: 40,
    },
    headerActions: {
        width: 88,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
    },
    headerIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.surface,
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
    },
    avatarContainer: {
        alignItems: 'center',
        marginTop: 12,
        marginBottom: 12,
    },
    infoCard: {
        backgroundColor: '#141422',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.08)',
        marginBottom: 8,
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 6,
    },
    infoLabel: {
        color: '#9CA3AF',
        fontSize: 13,
        fontWeight: '600',
    },
    infoValue: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: '700',
    },
    divider: {
        height: 1,
        backgroundColor: 'rgba(255, 255, 255, 0.06)',
        marginVertical: 6,
    },
    badgeRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    badge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 16,
        backgroundColor: 'rgba(107, 114, 128, 0.2)',
    },
    badgeVerified: {
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.4)',
    },
    badgeIcon: {
        marginRight: 6,
    },
    badgeTextVerified: {
        color: '#10B981',
        fontSize: 12,
        fontWeight: '700',
    },
    profileContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 28,
    },
    profileSummary: {
        alignItems: 'center',
        paddingVertical: 8,
        marginBottom: 22,
    },
    avatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    avatarFallback: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: colors.surface,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.primary,
    },
    avatarFallbackText: {
        color: colors.text,
        fontSize: 28,
        fontWeight: '800',
    },
    libraryTitle: {
        color: colors.text,
        fontSize: 16,
        fontWeight: '800',
        marginBottom: 10,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    historyChevron: {
        marginLeft: 2,
        marginTop: -10,
    },
    historyShelf: {
        paddingBottom: 18,
        gap: 12,
    },
    historyCard: {
        width: 148,
    },
    historyThumbnail: {
        width: 148,
        height: 84,
        borderRadius: 10,
        backgroundColor: colors.surface,
    },
    historyThumbnailFallback: {
        width: 148,
        height: 84,
        borderRadius: 10,
        backgroundColor: colors.surface,
    },
    historyTitle: {
        color: colors.text,
        fontSize: 12,
        fontWeight: '700',
        lineHeight: 17,
        marginTop: 7,
    },
    historyEmpty: {
        minHeight: 58,
        paddingHorizontal: 14,
        marginBottom: 18,
        borderRadius: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.surface,
    },
    historyEmptyText: {
        flex: 1,
        color: colors.muted,
        fontSize: 13,
        fontWeight: '600',
    },
    libraryList: {
        marginBottom: 8,
    },
    libraryRow: {
        minHeight: 92,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    libraryThumbnail: {
        width: 118,
        height: 72,
        borderRadius: 10,
        marginRight: 12,
        backgroundColor: colors.surface,
    },
    libraryThumbnailFallback: {
        width: 118,
        height: 72,
        borderRadius: 10,
        marginRight: 12,
        backgroundColor: '#242431',
    },
    libraryCopy: {
        flex: 1,
        paddingRight: 12,
    },
    libraryRowTitle: {
        color: colors.text,
        fontSize: 13,
        fontWeight: '800',
    },
    libraryRowSubtitle: {
        color: colors.muted,
        fontSize: 11,
        lineHeight: 16,
        marginTop: 4,
    },
    creatorName: {
        color: colors.text,
        fontSize: 20,
        fontWeight: '800',
        marginTop: 10,
    },
    creatorEmail: {
        color: colors.muted,
        fontSize: 13,
        marginTop: 4,
    },
    creatorBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        paddingHorizontal: 9,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
    },
    creatorBadgeText: {
        color: '#10B981',
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 5,
    },
    tabContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#141422',
        borderRadius: 10,
        padding: 4,
        marginBottom: 14,
    },
    tabButton: {
        flex: 1,
        paddingVertical: 8,
        alignItems: 'center',
        borderRadius: 8,
    },
    activeTabButton: {
        backgroundColor: colors.primary || '#6366F1',
    },
    tabText: {
        color: '#9CA3AF',
        fontSize: 11,
        fontWeight: '600',
    },
    activeTabText: {
        color: '#FFFFFF',
        fontWeight: '700',
    },
    logoutButton: {
        backgroundColor: colors.primary,
        borderRadius: 14,
        height: 48,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 10,
    },
    logoutButtonPressed: {
        opacity: 0.85,
    },
    logoutIcon: {
        marginRight: 8,
    },
    logoutButtonText: {
        color: colors.text,
        fontSize: 14,
        fontWeight: '700',
    },
});
